
alter table if exists tb_movie_genre
    drop constraint if exists FK633krcp7r6jm50sxq53j3wbw4;

alter table if exists tb_movie_genre
    drop constraint if exists FK813y3ntqxvet56li05s0b6ve4;

alter table if exists tb_user_genre
    drop constraint if exists FKcwtmv83nm7yy0elwwgoj6bwcp;

alter table if exists tb_user_genre
    drop constraint if exists FKm5ew0c2c7ydtbtjbnofrco5ys;

alter table if exists tb_user_role
    drop constraint if exists FK6g6aaa2yginq4fp9k1tg6ls3r;

alter table if exists tb_user_role
    drop constraint if exists FKpn4njnr07hiiam9pg4pp3xan7;

drop table if exists tb_genres cascade;

drop table if exists tb_movie_genre cascade;

drop table if exists tb_movies cascade;

drop table if exists tb_roles cascade;

drop table if exists tb_user_genre cascade;

drop table if exists tb_user_role cascade;

drop table if exists tb_users cascade;

create table tb_genres (
                           id bigint generated by default as identity,
                           name varchar(255),
                           primary key (id)
);

create table tb_movie_genre (
                                _value float(53),
                                genre_id bigint,
                                id bigint generated by default as identity,
                                movie_id bigint,
                                primary key (id)
);

create table tb_movies (
                           id bigint generated by default as identity,
                           description varchar(255),
                           title varchar(255),
                           primary key (id)
);

create table tb_roles (
                          id bigint generated by default as identity,
                          authority varchar(255),
                          primary key (id)
);

create table tb_user_genre (
                               _value float(53) DEFAULT 1.0,
                               genre_id bigint,
                               id bigint generated by default as identity,
                               user_id bigint,
                               primary key (id)
);

create table tb_user_role (
                              role_id bigint not null,
                              user_id bigint not null,
                              primary key (role_id, user_id)
);

create table tb_users (
                          id bigint generated by default as identity,
                          email varchar(255),
                          first_name varchar(255),
                          last_name varchar(255),
                          password varchar(255),
                          username varchar(255),
                          primary key (id)
);

alter table if exists tb_movie_genre
    add constraint FK633krcp7r6jm50sxq53j3wbw4
        foreign key (genre_id)
            references tb_genres;

alter table if exists tb_movie_genre
    add constraint FK813y3ntqxvet56li05s0b6ve4
        foreign key (movie_id)
            references tb_movies;

alter table if exists tb_user_genre
    add constraint FKcwtmv83nm7yy0elwwgoj6bwcp
        foreign key (genre_id)
            references tb_genres;

alter table if exists tb_user_genre
    add constraint FKm5ew0c2c7ydtbtjbnofrco5ys
        foreign key (user_id)
            references tb_users;

alter table if exists tb_user_role
    add constraint FK6g6aaa2yginq4fp9k1tg6ls3r
        foreign key (role_id)
            references tb_roles;

alter table if exists tb_user_role
    add constraint FKpn4njnr07hiiam9pg4pp3xan7
        foreign key (user_id)
            references tb_users;
